version: '1.5'

services:
  postgresql:
    image: grem4/postgresql:9.5
    environment:
    - DB_USER=redmine
    - DB_PASS=secret_password
    - DB_NAME=redmine
    volumes:
    - /srv/docker/redmine/postgresql:/var/lib/postgresql

  redmine:
    image: grem4/redmine:3.3.0
    depends_on:
    - postgresql
    environment:
    - TZ=Europe/Kyiv

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=redmine
    - DB_PASS=secret_password
    - DB_NAME=redmine

    - REDMINE_PORT=10101
    - REDMINE_HTTPS=false
    - REDMINE_RELATIVE_URL_ROOT=
    - REDMINE_SECRET_TOKEN=

    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=5

    - REDMINE_CONCURRENT_UPLOADS=5

    - REDMINE_BACKUP_SCHEDULE=
    - REDMINE_BACKUP_EXPIRY=
    - REDMINE_BACKUP_TIME=

    - SMTP_ENABLED=false
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=www.testmail.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=smtp_user@testmail.com
    - SMTP_PASS=smtp_secret_password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=imap_user@testmail.com
    - IMAP_PASS=imap_secret_password
    - IMAP_SSL=true
    - IMAP_INTERVAL=30

    ports:
    - "10101:80"
    volumes:
    - /srv/docker/redmine/redmine:/home/redmine/data
